setup.py

This is workaround. Latest jedi version 0.8.1-final0 but this is
invalid version for Python. This makes some issue such as #184.
This workaround will be removed if valid version jedi will be released
in the future.

Install jedi 0.8.1.

---

jedi.el

jedi expects tab is 1 character(not 8 spaces).

Fix tab indentation issue

---

jedi.el

Without the autoload you need to explicitly load `jedi` otherwise
calling `jedi-mode` fails with `(void-function jedi:auto-complete-mode)`

Autoload the function `jedi:auto-complete-mode`

---

jediepcserver.py
test_jediepcserver.py

I use couple of hosts with different hostnames and expanding `~` in virtualenv paths would simplify such use case a lot.
Also, I couldn't resist tweaking api a bit to separate concerns and make it clearer what's going on.

jediepcserver.py: expand user (~) and env vars in virtual-env argument

---

jedi.el

This PR fixes `jedi:dot-complete` interaction with prefix args:
- if prefix arg is used, requested number of dots is inserted
- don't try to complete if prefix-arg is not 1
- using `self-insert-command` makes overwrite mode work without hacks and also allows `jedi:dot-complete` to be bound to any key (not only `.`)

Fix jedi:dot-complete to work with prefix argument

---

jedi.el

This patch finishes up the renaming process in #218 and fixes the "Wrong type argument: number-or-marker-p, nil" error that Emacs gives when trying to run "jedi:dot-complete".

Rename "prefix-arg" in "jedi:dot-complete"

---

jedi-core.el

Sending nil makes error.
This is related to #221.

Send empty string if buffer is visited with file

---

jediepcserver.py

They were removed at jedi 0.9.0.
This is related to #228

Don't use deprecated attributes

---

jediepcserver.py
setup.py

jedi 0.9.0 is released now.
This is related to #184 etc.

Remove workaround of invalid jedi version issue

---

jediepcserver.py
test_jediepcserver.py

As per #178, python 3 venv weren't properly added to path for jedi.
Rather than using sys.version to figure out python version, allow any
python version to be added. The code was taken #223 and I fixed failing
testcase.

Support any python version

---

jedi.el

If I understand the code correctly, the purpose of `jedi:after-change-handler` is to change the value of `jedi:defined-names--cache`.  
And this value is used for only functions which is related to `jedi` and `imenu`.  
So if `jedi:install-imenu` is `nil`, `jedi:after-change-handler` should not be added to `after-change-functions`. I think this commit will fix #234.

Do not change after-change-functions when jedi:install-imenu is nil.

---

jediepcserver.py

'doc' was deprecated interface from 0.8.0.

Use docstring instead of doc

---

jedi-core.el

This is related to https://github.com/syohex/emacs-company-jedi/issues/13.
CC: @yusekiya

Don't show jedi tooltip when company tooltip is enabled

---

jediepcserver.py

This PR adds new command line parameters that configure log rotation:
- `--log-rotate-max-size` sets maximum size of the log file after which it's rotated
- `--log-rotate-max-count` sets maximum number of rotated log files after which the oldest ones are removed

jediepcserver.py: add log rotate configuration

---

jediepcserver.py

This PR adds a `--sys-path-append` parameter. I find the parameter useful to provide fallback completions, for example one can have emacs-jedi's virtualenv installed last in the `sys.path` list, so that if there's no jedi around it would be used, but if a jedi is installed in the target virtualenv (it comes with ipython now, so not a rare sighting) so that one would be used instead.

jediepcserver.py: add --sys-path-append parameter

---

.travis.yml
jedi-core.el
test_jediepcserver.py
tox.ini

This PR contains a fix for #299 and an update for tox.ini to enable testing with jedi versions 0.11 and 0.12

More random fixes

---

jedi-core.el

- Add a hook allowing code to be executed after jumping to a definition.
- For example, I use this to expand any code-folding that is in effect, and call `pulse-momentary-highlight-one-line`
- Made the code change locally, used `add-hook` to add a hook function and confirmed it worked as expected.

Add jedi:goto-definition-hook

---

jedi-core.el

There are times when it would be helpful to be able to put jedi's displays into a particular window or frame.  This can be done with this simple change which allows binding a custom function that finds the file, line and column that jedi provides, thereby controlling where it is displayed.
I hope you will integrate this.  I also fixed a few doc language issues.

Add jedi:find-file-function to control where outputs are displayed.

---

jediepcserver.py
test_jediepcserver.py

This PR fixes `complete` request to return empty strings for all exceptions that may be raised from `comp.docstring()` method, not just `KeyError`. 
Should fix #339.

Ignore all errors when getting completion docstrings

---

.travis.yml

With Trusty already EOLed we need to migrate to Xenial soon.

travis.yml: use xenial distro, list emacs versions provided by evm

---

.travis.yml
Makefile
jedi-core.el
jediepcserver.py
setup.py
test-jedi.el
test_jediepcserver.py
tox.ini

I noticed the completion was broken after upgrading my emacs setup and looked a bit into it.
Jedi 0.18 seems to drop old, unmaintained python releases and to rename a few class/methods, breaking the epcserver (emit a warning in 0.17.X) :
- line / column are now passed at the method call instead of the jedi.Script init. I didn't want to break the epcserver interface so I've just split the *args to dispatch the parameter where needed. 
- renamed a few calls (call_signatures is now get_signatures, ...)
- the desc_with_module attribute is no more available in jedi api (no replacement for now). I've put full_name instead so the method call don't fail but we may want some other value here.
So far, the completion/definition jump is back (using latest company-jedi and fresh emacs master build) …

Jedi 0.18 update

---

.gitmodules

Github no longer permits unencrypted methods like http:// or git://, resulting in an error like:
```
The unauthenticated git protocol on port 9418 is no longer supported.
```
Using https:// avoids the issue.

Update sphinx-eldomain submodule to use https URL.
